### PR TITLE
Made the website static to render from GitHub 

### PR DESCRIPTION
**Pull request by DefCon-007**
You test the website at https://defcon-007.github.io/2016/ . 
Ping @OrkoHunter

### CODE REVIEW

**Review by OrkoHunter — CHANGES_REQUESTED** [review]
1. Inside About,

i. replace `program
for the students of IIT Kharagpur` with `program for students`

ii. replace `program will not only help students to get involved in open source, but will also prep` with `program not only helps students to get involved in open source, but also preps`

iii. Remove both "get involved" lines containing form link for student and mentor. Leave it with the resources button

2. Fill up github handles using google searches, koss contact sheet for members and/or emailing them.

**Comment by OrkoHunter** [comment]
Great job @DefCon-007 !

**Comment by OrkoHunter** [comment]
After making the suggested changes, please merge the PR yourself.

**Comment by americast** [comment]
@DefCon-007 Could you make the 'o' of "KWOC" small ?

**Comment by OrkoHunter** [comment]
@americast I tried making the change with inspect view, and do be honest I like the one with capital 'o'. We have the full name in the left top and which is fairly visible so, I won't recommend to change the orientation of 'o'.

**Comment by americast** [comment]
@OrkoHunter Very true indeed. Keeping it all caps is looking better. But, I guess, maintaining consistency is an integral part of a professional website. May be we could have it in another way, like, `1 month, 100+ commits, 40+ students`, just like the GSoC page :stuck_out_tongue: ?

**Comment by OrkoHunter** [comment]
@americast Consistency like metaKGP, MetaKGP and metakgp ? :P It's cool.

**Comment by DefCon-007** [comment]
@OrkoHunter Merging it now. The handles can be updates later.

**Pull request merged**
